### ISSUE TITLE
Thumbnail Missing

### ISSUE THREAD

**Issue by drfujisawa** [xjcl/planetmoney-rss#3]
In you example screenshots the podcast has a thumbnail, but for me it does not. I am using Overcast on iOS.

**Comment by xjcl** [comment]
Thanks a lot for your contribution! It appears like the URL linking to the image is a dead link now:
- https://www.nationalpublicmedia.com/wp-content/uploads/2014/06/planetmoney.png

I replaced it with this URL:
- https://media.npr.org/assets/img/2018/08/02/npr_planetmoney_podcasttile_sq-7b7fab0b52fd72826936c3dbe51cff94889797a0.jpg?s=1400

Please try either (1) updating or (2) removing and then re-adding the podcast, and tell me if this fixed the issue.

**Comment by drfujisawa** [comment]
Yes. The issue is fixed

**Comment by xjcl** [comment]
Glad to hear it! :)
