### ISSUE TITLE
The Indicator Fork

### ISSUE THREAD

**Issue by drfujisawa** [xjcl/planetmoney-rss#4]
Indicator fork needs changes. Want version of this feed but for The Indicator.

Sorry if I am not going about this in the right way

**Comment by xjcl** [comment]
I tried looking at some old episodes of The Indicator but the links seem dead so there isn't anything I can do. Plus I think Apple has removed the 300-episode limit in the meantime, as evidenced by Planet Money having 372 episodes on there now.
